/*
Amazon E-commerce SQL Case Study

This project analyzes sales, customer behavior, shipping performance,
and inventory management using SQL.

Key Skills Demonstrated:
- Complex Joins
- Window Functions
- Aggregations
- Business KPIs
- Customer Analytics
- Inventory Monitoring
*/


CREATE TABLE customers (customer_id BIGINT PRIMARY KEY,
first_name VARCHAR(50),
last_name VARCHAR(50),
state VARCHAR(50)
)
select * from customers

CREATE TABLE category 
(category_id INT PRIMARY KEY,
category_name VARCHAR(50)
)

CREATE TABLE sellers
(seller_id BIGINT PRIMARY KEY,
seller_name VARCHAR(50),
origin VARCHAR(30)
)

CREATE TABLE products
(product_id BIGINT PRIMARY KEY,
product_name VARCHAR(100),
price FLOAT ,
cogs FLOAT,
category_id INT REFERENCES category(category_id)
)

CREATE TABLE orders
(order_id BIGINT PRIMARY KEY,
order_date DATE,
customer_id BIGINT REFERENCES customers(customer_id),
seller_id BIGINT REFERENCES sellers(seller_id),
order_status VARCHAR(50)
)


CREATE TABLE payments
(payment_id int PRIMARY KEY ,
order_id  BIGINT REFERENCES orders(order_id),
payment_date DATE,
payment_status VARCHAR(50)
)

CREATE TABLE order_items
(order_item_id 	BIGINT PRIMARY KEY,
order_id BIGINT REFERENCES orders(order_id),
product_id BIGINT REFERENCES products(product_id),
quantity INT,
price_per_unit FLOAT
)


CREATE TABLE inventory
(inventory_id INT PRIMARY KEY,
product_id BIGINT REFERENCES products(product_id), 
stock INT,
warehouse_id INT,
last_stock_date DATE)

CREATE TABLE shipping
(shipping_id INT PRIMARY KEY,
order_id BIGINT REFERENCES order_items(order_item_id),
shipping_date DATE,
return_date DATE,
shippingproviders VARCHAR(50),
delivery_status VARCHAR(50)
)


;
select * from category;
select * from sellers;
select * from products;
select * from orders;
select * from payments;
select * from order_items;
select * from inventory
order by stock desc


select * from shipping
/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

select product_name,COUNT(ors.order_id),SUM(price * ord.quantity) AS totalsales from products p
join order_items ord
ON p.product_id = ord.product_id
join orders as ors
on ord.order_id = ors.order_id
GROUP BY 1
ORDER BY 3 DESC
LIMIT 10

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/



SELECT 
	category_name,
SUM(price_per_unit * oi.quantity) AS total_revenue,
100*SUM(price_per_unit * oi.quantity)::NUMERIC/SUM(SUM(price_per_unit * oi.quantity)) OVER() AS per_contro from category c
JOIN products p
ON c.category_id = p.category_id
join order_items oi
ON oi.product_id = p.product_id
GROUP BY 1
_______________________
or
_______________________
SELECT 
    c.category_name,
    SUM(oi.quantity * oi.price_per_unit) AS total_revenue,
    100 * SUM(oi.quantity * oi.price_per_unit) /
    (
        SELECT SUM(quantity * price_per_unit)
        FROM order_items
    ) AS percentage
FROM category c
JOIN products p 
ON c.category_id = p.category_id
JOIN order_items oi 
ON p.product_id = oi.product_id
GROUP BY c.category_name;

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

SELECT *FROM(
SELECT c.customer_id,first_name,COUNT(o.customer_id) AS countoforders,SUM(price_per_unit*quantity)AS totalorders,
SUM(price_per_unit*quantity)/COUNT(o.customer_id) AS AOV

FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON oi.order_id=o.order_id
GROUP BY 1,2)
WHERE countoforders>5


/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/


WITH tablea AS (
SELECT extract(MONTH FROM order_date)AS montha ,
extract(YEAR FROM order_date)AS years ,
SUM(quantity *price_per_unit) AS current_monthsales 
FROM orders o
JOIN order_items  oi
ON oi.order_id=o.order_id
GROUP BY 1,2
),
tableb AS (
SELECT montha ,years ,current_monthsales, LAG(current_monthsales,1) OVER( ORDER BY montha) AS premonthsales FROM tablea
WHERE years = 2024)

SELECT montha ,years ,current_monthsales,premonthsales,100*(current_monthsales - premonthsales)/premonthsales FROM tableb


/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/

SELECT * FROM customers WHERE customer_id NOT IN(SELECT DISTINCT 
    customer_id from orders)


OR
	
SELECT FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;



/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/


select * from(
	SELECT cr.state,category_name, COUNT(o.order_id),SUM(price_per_unit * quantity) AS totalsales ,
	RANK() OVER(PARTITION BY state ORDER BY COUNT(o.order_id)) AS rank
	FROM category c
	
	JOIN products p
	ON c.category_id = p.category_id
	JOIN order_items oi
	ON p.product_id = oi.product_id
	JOIN orders o
	ON oi.order_id = o.order_id
	JOIN customers cr
	ON cr.customer_id = o.customer_id
	GROUP BY 1,2
	order by 1
	)where rank =1



/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

select c.customer_id, first_name,COUNT(order_id) AS cltv from customers c
JOIN orders o 
ON o.customer_id = c.customer_id
GROUP BY 1,2
order by 3 DESC



/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

select i.*,
CASE
	WHEN stock >= 61 THEN 'optimal'
	WHEN stock>= 20 AND stock <=60 THEN 'havetoorder'
	ELSE 'urgent'
	END AS stock_level
	from inventory i
JOIN products p
ON i.product_id = p.product_id

/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/


	SELECT o.order_id,CONCAT(first_name,' ',last_name) AS fullname,o.order_date,s.shipping_date,
	s.shipping_date - o.order_date AS shippingdays,order_status 
	FROM orders o
	JOIN order_items oi
	ON o.order_id=oi.order_id
	JOIN shipping s
	ON oi.order_id = s.order_id 
	JOIN customers cs
	ON o.customer_id = cs.customer_id
	WHERE shipping_date - o.order_date > 3

/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

	
SELECT p.payment_status,COUNT(*) as totalcnt,
COUNT(*)::numeric/(SELECT COUNT(*)FROM payments)::numeric *100 AS PERCENTAGEBD
	FROM orders o
	JOIN customers cs
	ON o.customer_id = cs.customer_id
	JOIN payments p
	ON o.order_id= p.order_id
	GROUP BY 1




/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/


SELECT os.seller_id,seller_name,
COUNT(s.*) AS totalorders,
COUNT(*) FILTER (WHERE order_status='Completed')AS completed
,100* COUNT(*) FILTER (WHERE order_status='Completed')::NUMERIC /COUNT(s.*)::numeric AS per_succ
FROM sellers s
JOIN orders os
ON s.seller_id = os.seller_id
GROUP BY 1,2
Order by 3 DESC
LIMIT 5

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/


WITH mytab AS 
(
SELECT p.product_id,product_name,SUM(price_per_unit - cogs)AS profitmargin
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY 1,2
ORDER BY 1
)
SELECT product_name,profitmargin,
DENSE_RANK() OVER(ORDER BY profitmargin DESC) AS rank
FROM mytab

OR

SELECT 
	product_id,
	product_name,
	profit_margin,
	DENSE_RANK() OVER( ORDER BY profit_margin DESC) as product_ranking
FROM
(SELECT 
	p.product_id,
	p.product_name,
	SUM(total_sale - (p.cogs * oi.quantity))/sum(total_sale) * 100 as profit_margin
FROM order_items as oi
JOIN 
products as p
ON oi.product_id = p.product_id
GROUP BY 1, 2
) as t1


/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/

SELECT p.product_id,p.product_name,
COUNT(*) FILTER (WHERE order_status='Returned') AS returnedcount
FROM products p
JOIN order_items os
ON p.product_id = os.product_id
JOIN orders o
ON os.order_id = o.order_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10

/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/

(SELECT * FROM sellers
WHERE seller_id NOT IN (SELECT seller_id FROM orders WHERE order_date >= CURRENT_DATE - INTERVAL '6 month')



/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 20 months.
Challenge: Show the last sale date and total sales from those sellers.
*/

select s.seller_id,seller_name,
SUM(price_per_unit *quantity)AS totalsales,MAX(o.order_date)AS lastsaledate
from sellers s
LEFT JOIN orders o
ON s.seller_id = o.seller_id
LEFT JOIN order_items oi
ON o.order_id = oi.order_id 
GROUP BY 1,2
HAVING MAX(o.order_date) < CURRENT_DATE - INTERVAL '20 month'

OR


WITH cte1 -- as these sellers has not done any sale in last 6 month
AS

(
SELECT * FROM sellers
WHERE seller_id NOT IN (SELECT seller_id FROM orders WHERE order_date >= CURRENT_DATE - INTERVAL '20 month')
)
SELECT 
o.seller_id,
MAX(o.order_date) as last_sale_date
FROM orders as o
JOIN 
cte1
ON cte1.seller_id = o.seller_id
JOIN order_items as oi
ON o.order_id = oi.order_id
GROUP BY 1

/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/

SELECT * FROM
(
SELECT c.customer_id,
SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS totalreturned
FROM  customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY 1
)
WHERE totalreturned > 5


/*
17. Cross-Sell Opportunities
Find customers who purchased product A but not product B (e.g., customers who bought AirPods but not AirPods Max).
Challenge: Suggest cross-sell opportunities by displaying matching product categories.
*/

select * from customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE p.product_name LIKE '%AirPods%'
 AND c.customer_id NOT IN (
    SELECT c2.customer_id
    FROM customers c2
    JOIN orders o2 ON c2.customer_id = o2.customer_id
    JOIN order_items oi2 ON o2.order_id = oi2.order_id
    JOIN products p2 ON oi2.product_id = p2.product_id
    WHERE p2.product_name LIKE '%AirPods Max%'
  );
OR
SELECT c.customer_id
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY c.customer_id
HAVING SUM(CASE WHEN p.product_name LIKE '%ProductA%' THEN 1 ELSE 0 END) > 0
   AND SUM(CASE WHEN p.product_name LIKE '%ProductB%' THEN 1 ELSE 0 END) = 0;
   
/*
18. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/


SELECT 
	c.state,
	CONCAT(c.first_name, ' ', c.last_name) as customers,
	COUNT(o.order_id) as total_orders,
	SUM(price_per_unit * quantity) as total_sale,
	DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(o.order_id) DESC) as rank
	FROM orders as o
	JOIN 
	order_items as oi
	ON oi.order_id = o.order_id
	JOIN 
	customers as c
	ON 
	c.customer_id = o.customer_id
	GROUP BY 1,2
	WHERE rank <= 5

/*
19. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/

SELECT 
	s.shippingproviders,
	COUNT(o.order_id) as order_handled,
	SUM(price_per_unit * quantity) as total_sale,
	COALESCE(AVG(s.return_date - s.shipping_date), 0) as average_days
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
shipping as s
ON 
s.order_id = o.order_id
GROUP BY 1

SELECT * FROM shipping


---Thanks 
	